version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
  server:
    restart: always
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/app"
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
  db:
    restart: always
    image: sameersbn/postgresql:10-2
    ports:
      - "5432:5432"
    environment:
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=series_app
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
